# Generated by Django 4.2.19 on 2025-02-10 14:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_programminglanguage_codesnippet_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='codesnippet',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='disliked_snippets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='codesnippet',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_snippets', to=settings.AUTH_USER_MODEL),
        ),
    ]
