# Generated by Django 4.2.19 on 2025-02-15 16:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_tag_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codesnippet',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='codesnippet',
            name='dislikes',
            field=models.ManyToManyField(related_name='disliked_snippets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='codesnippet',
            name='likes',
            field=models.ManyToManyField(related_name='liked_snippets', to=settings.AUTH_USER_MODEL),
        ),
    ]
