# Generated by Django 4.2.19 on 2025-02-16 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_category_options_category_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programminglanguage',
            name='code',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='code',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_snippets', to='api.programminglanguage'),
        ),
    ]
